{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_user\",\"data_bq\",\"city\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "023d4d6f-9387-4da1-bc60-b1486c9b0c29",
        "fromColumn": "v_datetime",
        "fromTable": "data_bq",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e7606fd0-4366-444e-886f-2ef96ccc8b6a"
      },
      {
        "name": "8287206d-c143-47ee-aa19-df78cb79eb42",
        "fromColumn": "user_id",
        "fromTable": "data_bq",
        "toColumn": "nik",
        "toTable": "dim_user"
      },
      {
        "name": "b8f0a44a-e519-4fa6-8f22-b9d510b7ecf6",
        "fromColumn": "Date",
        "fromTable": "#dim_date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c24775e0-a582-432b-86ed-03085b6aaf28"
      },
      {
        "name": "f8a7b949-8e3a-c7f8-0a4e-16bccc55edf5",
        "fromColumn": "v_date",
        "fromTable": "data_bq",
        "toColumn": "Date",
        "toTable": "#dim_date"
      },
      {
        "name": "cf437418-57e2-51e5-bba7-0eefc2ec38cf",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "witel",
        "fromTable": "dim_user",
        "toCardinality": "many",
        "toColumn": "witel",
        "toTable": "city"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_user",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nik",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "421d11a5-6ae0-497a-9f29-dca0561d6d71",
            "sourceColumn": "nik",
            "summarizeBy": "none"
          },
          {
            "name": "fullname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcc8363b-5f83-487f-a379-0dd71e460167",
            "sourceColumn": "fullname",
            "summarizeBy": "none"
          },
          {
            "name": "jobtitle_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ed63ebd-11b4-4872-82ae-c7782175dc82",
            "sourceColumn": "jobtitle_category",
            "summarizeBy": "none"
          },
          {
            "name": "role_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d82d5d1-6b40-44ac-9e70-73a6ba57ea05",
            "sourceColumn": "role_name",
            "summarizeBy": "none"
          },
          {
            "name": "division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e536b6c4-8877-45c1-ba1f-8ecd7c8e9f7d",
            "sourceColumn": "division",
            "summarizeBy": "none"
          },
          {
            "name": "regional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20725157-fccb-413c-817f-9f9026109bb7",
            "sourceColumn": "regional",
            "summarizeBy": "none"
          },
          {
            "name": "witel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77f55ad4-9b0b-4fb7-bed9-b370ab7facc1",
            "sourceColumn": "witel",
            "summarizeBy": "none"
          },
          {
            "name": "row_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca11da45-19ce-4044-8ec7-5645164cba55",
            "sourceColumn": "row_num",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1e2de885-4d89-4b36-9422-a39506a430b3",
        "partitions": [
          {
            "name": "dim_user",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(PostgreSQL.Database(\"localhost:9999\", \"mytens\"), \"select * from (#(lf)select nik, fullname, jobtitle_category, role_name, division, regional, witel, #(lf)ROW_NUMBER() OVER (PARTITION BY nik ORDER BY nik) AS row_num#(lf)from mytens_datamart.s3_user_management_mytens#(lf)) as data1#(lf)where row_num=1\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_bd471a8b-d863-461e-95f6-a78655ca5ff3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "29f7b23f-7a30-44d2-b9d5-5df3509b4bce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5b7d6fa2-d91d-4775-9705-baaca6cc720a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3b06da8b-22dd-4a6b-817f-ffaf3eb3fbbf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6cf489a1-9fbd-4055-ba90-742f1b19eead",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ac828cfd-8c8f-4d97-8a9f-d5500748f635",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a243a82b-7dca-472a-ab12-283b6d98c1d7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2c14612-3ec4-4260-ac9a-be7319418ad0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f5878f2a-4e59-4792-9223-f485544656d5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2531a454-51ff-469f-b5dc-9558fe24fe1a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6e08ad6d-faa0-40f1-bd2b-e7945fb535cf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "22e4ea51-48c4-42ac-bf32-955609c4fa58",
                "ordinal": 3
              }
            ],
            "lineageTag": "6e9d5c26-c4f9-4299-a561-7c19abcf6f1b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "97c499aa-fd42-491d-b458-8307b5d48628",
        "partitions": [
          {
            "name": "DateTableTemplate_bd471a8b-d863-461e-95f6-a78655ca5ff3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "data_bq",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "v_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fbf0ffd7-4bf2-4d71-8db9-ce56eeef9517",
            "sourceColumn": "v_date",
            "summarizeBy": "none"
          },
          {
            "name": "v_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "4ad76804-e4a1-47f4-89cc-0ee810288720",
            "sourceColumn": "v_time",
            "summarizeBy": "none"
          },
          {
            "name": "v_datetime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0d593bcc-652e-4d81-acde-8fbd02044617",
            "sourceColumn": "v_datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e7606fd0-4366-444e-886f-2ef96ccc8b6a"
                },
                "isDefault": true,
                "relationship": "023d4d6f-9387-4da1-bc60-b1486c9b0c29"
              }
            ]
          },
          {
            "name": "event_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d68b172b-2f21-4750-b9a9-99dbd0253fed",
            "sourceColumn": "event_date",
            "summarizeBy": "none"
          },
          {
            "name": "event_timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b52f62ee-cf88-44d7-bad3-48d638cf2e66",
            "sourceColumn": "event_timestamp",
            "summarizeBy": "sum"
          },
          {
            "name": "event_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c251b5a-0926-4f51-aa26-20d9d46f109f",
            "sourceColumn": "event_name",
            "summarizeBy": "none"
          },
          {
            "name": "page_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a00bf9cd-115a-444c-8455-d1e2d233c261",
            "sourceColumn": "page_title",
            "summarizeBy": "none"
          },
          {
            "name": "page_location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc4075c-de7c-4253-8319-ffdf89055a4d",
            "sourceColumn": "page_location",
            "summarizeBy": "none"
          },
          {
            "name": "page_referrer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39f9ad2f-d118-46bd-999f-a454711b08f5",
            "sourceColumn": "page_referrer",
            "summarizeBy": "none"
          },
          {
            "name": "ga_session_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66fb22d1-8f4a-41a7-9982-041d1d6ce062",
            "sourceColumn": "ga_session_id",
            "summarizeBy": "sum"
          },
          {
            "name": "ga_session_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bf25892-a7a1-43db-a6ee-bdfd552e9143",
            "sourceColumn": "ga_session_number",
            "summarizeBy": "sum"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1840cd9-f4f8-487f-842a-072c32b1644a",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "user_pseudo_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f31dd0d-6f25-4d66-bcbc-8026e8b64308",
            "sourceColumn": "user_pseudo_id",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af289038-5539-4c4a-aa43-0f27608f26d7",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "mobile_brand_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7536a9f8-cd29-492f-94ee-0d62506eff3f",
            "sourceColumn": "mobile_brand_name",
            "summarizeBy": "none"
          },
          {
            "name": "mobile_model_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b220743-a125-4612-b7ee-35d73bd98df2",
            "sourceColumn": "mobile_model_name",
            "summarizeBy": "none"
          },
          {
            "name": "mobile_marketing_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9422566-ac48-4a10-919a-2a09a5f8cd97",
            "sourceColumn": "mobile_marketing_name",
            "summarizeBy": "none"
          },
          {
            "name": "operating_system",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b19c39d5-f72c-41bf-8961-dd16eda7d103",
            "sourceColumn": "operating_system",
            "summarizeBy": "none"
          },
          {
            "name": "operating_system_version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58cce9b8-76f4-4084-9ab0-ed0e2529ea46",
            "sourceColumn": "operating_system_version",
            "summarizeBy": "none"
          },
          {
            "name": "browser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "328c1e55-c253-4e53-bd6f-96fd9129c03d",
            "sourceColumn": "browser",
            "summarizeBy": "none"
          },
          {
            "name": "hostname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cc175b0-c1e7-4b39-ac8b-022335923e65",
            "sourceColumn": "hostname",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49a38c22-e168-417a-9d3b-f2432ce9ccaf",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb9606f8-28e8-4bf4-8cb0-841f996b4c50",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b3ff45a-63c4-4e8c-a7ec-cfaef95dde1f",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "medium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "908b5865-e02e-404d-954b-a01add9743dc",
            "sourceColumn": "medium",
            "summarizeBy": "none"
          },
          {
            "name": "source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b53d599-4a84-4573-8eac-caff5c45f5aa",
            "sourceColumn": "source",
            "summarizeBy": "none"
          },
          {
            "name": "platform",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98647d97-5296-462b-b174-05541d893845",
            "sourceColumn": "platform",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cf7b0a6b-5aa1-4d55-9a3f-a52bbac9456f",
        "partitions": [
          {
            "name": "data_bq",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=\"gobeyond-mytens-prod\"]){[Name=\"gobeyond-mytens-prod\"]}[Data], \"SELECT  #(lf)    DATE(TIMESTAMP_MICROS(event_timestamp), \"\"Asia/Jakarta\"\") v_date,#(lf)    TIME(TIMESTAMP_MICROS(event_timestamp), \"\"Asia/Jakarta\"\") v_time,#(lf)    DATETIME(TIMESTAMP_MICROS(event_timestamp), \"\"Asia/Jakarta\"\") v_datetime,#(lf)    event_date, event_timestamp, event_name,#(lf)    (select value.string_value from unnest(event_params) where key='page_title') as page_title,#(lf)    (select value.string_value from unnest(event_params) where key='page_location') as page_location,#(lf)    (select value.string_value from unnest(event_params) where key='page_referrer') as page_referrer,#(lf)    (select value.int_value from unnest(event_params) where key='ga_session_id') as ga_session_id,#(lf)    (select value.int_value from unnest(event_params) where key='ga_session_number') as ga_session_number,#(lf)    user_id, user_pseudo_id, device.category, device.mobile_brand_name,#(lf)    device.mobile_model_name, device.mobile_marketing_name, #(lf)    device.operating_system, device.operating_system_version,#(lf)    device.web_info.browser, device.web_info.hostname,#(lf)    geo.country, geo.region, geo.city,#(lf)    traffic_source.medium, traffic_source.source, platform#(lf)    FROM `gobeyond-mytens-prod.analytics_412886279.events_*`#(lf)where  event_name not in ('first_visit',#(lf)    'session_start',#(lf)    'click',#(lf)    'scroll',#(lf)    'form_start',#(lf)    'gtm.dom',#(lf)    'user_engagement','form_submit') and user_id not like '%dummy%' and user_id NOT LIKE '%admin%' and stream_id = '6310182590'#(lf)    and DATE(TIMESTAMP_MICROS(event_timestamp), \"\"Asia/Jakarta\"\") > DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY)\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e7606fd0-4366-444e-886f-2ef96ccc8b6a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0b3c37d0-4115-4f64-b893-8e3b6681bab3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "23451c07-3131-469a-9669-829b87dc752c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c0a2a6c9-7c80-4241-a68d-6751bb1a3393",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "81f6f8e7-942a-4441-81ea-d31cceba9e28",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cafe35bd-5e43-4869-95ea-f93905686ef1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "55551de4-0fd2-4767-a57d-87b9f53f8d35",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d030707e-609c-4399-80ef-de84da7511ef",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3bbb678e-5c74-45f7-adb8-ea25b5293dec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3d97538f-4a0a-4a75-bb5e-b262dd2bdc91",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3cdaf9bd-d1c3-4459-8df0-36de835f344a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ce9c1374-010a-41b6-b076-2638d6b22dff",
                "ordinal": 3
              }
            ],
            "lineageTag": "7d1cae0b-aa24-4ea5-a3b9-607847b78052"
          }
        ],
        "isHidden": true,
        "lineageTag": "6a956899-2046-4579-a510-6e4143df5ef0",
        "partitions": [
          {
            "name": "LocalDateTable_e7606fd0-4366-444e-886f-2ef96ccc8b6a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('data_bq'[v_datetime])), 1, 1), Date(Year(MAX('data_bq'[v_datetime])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "#dim_date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "03bd531747334d5da0d55ef46ec0e4b3"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aaa8fbad-c163-4374-a626-f750419b617a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c24775e0-a582-432b-86ed-03085b6aaf28"
                },
                "isDefault": true,
                "relationship": "b8f0a44a-e519-4fa6-8f22-b9d510b7ecf6"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b0d049a4-cc92-495c-8483-bf6c313f2e6f",
            "sourceColumn": "[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ac12add1-5aa8-483e-8735-51a9c24d6c80",
            "sourceColumn": "[Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ae7636f4-6881-4457-b6ae-6e1b18274c52",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PERIOD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cdceec70-4af8-4369-8a4d-1ae5af473b48",
            "sourceColumn": "[PERIOD]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "701a8c6e-af21-4dcf-af31-9f7f8d4b9711",
            "sourceColumn": "[DateMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "98900add-28c2-4421-a255-04e779ff6436",
            "sourceColumn": "[MMDD]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "30bb4838-88f2-4e3c-b991-b63f09c4a4f7",
            "sourceColumn": "[Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "mmmDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fe5827fb-ceb7-4ea5-bac4-7e1d6f206858",
            "sourceColumn": "[mmmDD]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YYYYMMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a5a2fe99-22c3-464f-ac6f-dd4dd5586d49",
            "sourceColumn": "[YYYYMMDD]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "25a1fb68-39b0-4cf3-adc8-469f73d816f9",
        "partitions": [
          {
            "name": "#dim_date",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(",
                "    CALENDAR(min(data_bq[v_date]), max(data_bq[v_date])),",
                "    \"Year\", YEAR([Date]),",
                "    \"Month\", MONTH([Date]),",
                "    \"MonthText\", FORMAT([Date], \"mmm\"),",
                "    \"PERIOD\", FORMAT([Date], \"YY-MM\"),",
                "    \"DateMonth\", FORMAT([Date], \"DD-mmm\"),",
                "    \"MMDD\", FORMAT([Date], \"MM-DD\"),",
                "    \"Week\", FORMAT([Date], \"YY-ww\"), ",
                "    \"mmmDD\", FORMAT([Date], \"mmm-DD\"),",
                "    \"YYYYMMDD\", FORMAT([Date], \"YYYY-MM-DD\")",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c24775e0-a582-432b-86ed-03085b6aaf28",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bfd765bd-b253-4f82-b382-7ca7dbe72485",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3bd90c55-a1fb-444c-86ef-6d4484718533",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d766fb2e-594d-4598-9dfb-9a0f57b617c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "00da1dd3-bce6-4e3b-9b23-3f16a547e6a0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5d011f51-f0bb-41b4-a265-3d787e616c6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5978f6ef-e0ca-4f7f-a4f9-c35a338708af",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7bdaa6b3-8791-43da-bbdc-4ae2497c382a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "57d773c7-0b0e-4c85-a637-21f18f3664d4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "715c2814-5e46-49ae-bda8-bb98bf0e6789",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "65183b5c-6988-4afc-a99e-859d6e8a4cfc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "95e2c008-02fd-40ee-b88e-a21cfa53bb85",
                "ordinal": 3
              }
            ],
            "lineageTag": "4adac463-0606-41c1-bee8-71313c3f0eee"
          }
        ],
        "isHidden": true,
        "lineageTag": "beca8d1b-8a1a-4280-861f-48793fd0f539",
        "partitions": [
          {
            "name": "LocalDateTable_c24775e0-a582-432b-86ed-03085b6aaf28",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('#dim_date'[Date])), 1, 1), Date(Year(MAX('#dim_date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "#metrics",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dc77359389b54cbc82e17ee15842f9b6"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5258af71-4dca-4630-ad79-fdaf17c91b0c",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "12c79573-d093-4b81-a4e8-3c7d9223b3e1",
        "measures": [
          {
            "name": "user",
            "expression": [
              "DISTINCTCOUNT(data_bq[user_id])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "09202822-c478-46a9-84c4-a514e176b98c"
          }
        ],
        "partitions": [
          {
            "name": "#metrics",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1,1,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "city",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "regional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "267aac91-f353-478b-b80b-16b4eed97a3e",
            "sourceColumn": "regional",
            "summarizeBy": "none"
          },
          {
            "name": "witel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4623adbd-53fa-406f-868c-53c1a1503c77",
            "sourceColumn": "witel",
            "summarizeBy": "none"
          },
          {
            "name": "country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7058ac3e-1b93-46b3-9355-02d7beccaac3",
            "sourceColumn": "country",
            "summarizeBy": "none"
          },
          {
            "name": "province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ee2bb12-71b9-44a7-8cd4-288bdcbe915e",
            "sourceColumn": "province",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd32cb97-0bda-42c9-9c6b-5b691c38d1d0",
            "sourceColumn": "city",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "951f7f68-5594-4a3a-ad89-aac88eb38441",
        "partitions": [
          {
            "name": "city",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\LENOVO\\Downloads\\city - Sheet1.csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"regional\", type text}, {\"witel\", type text}, {\"country\", type text}, {\"province\", type text}, {\"city\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}