DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('data_tiket'[category])),
			AND(
				'data_tiket'[category] IN {"MyTEnS GoBeyond"},
				NOT('data_tiket'[category] IN {"NETMONK HI 2024"})
			)
		)

	VAR __DS0FilterTable2 = 
		TREATAS({2024}, '#dim_date'[Year])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				ROLLUPGROUP(
					'data_tiket'[additional_info_label_sub_sub_category],
					'data_tiket'[additional_info_label_sub_category]
				), "IsGrandTotalRowTotal"
			),
			__DS0FilterTable,
			__DS0FilterTable2,
			"TICKET", '#metrics'[TICKET],
			"TICKET_OPEN", '#metrics'[TICKET OPEN],
			"AVG_TIME_RESOLVED", '#metrics'[AVG TIME RESOLVED],
			"MIN_TIME_RESOLVED", '#metrics'[MIN TIME RESOLVED],
			"MAX_TIME_RESOLVED", '#metrics'[MAX TIME RESOLVED],
			"OVER_SLA", '#metrics'[OVER SLA]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			502,
			__DS0Core,
			[IsGrandTotalRowTotal],
			0,
			'data_tiket'[additional_info_label_sub_sub_category],
			1,
			'data_tiket'[additional_info_label_sub_category],
			1
		)

	VAR __DS0CoreNoInstanceFiltersNoTotals = 
		FILTER(KEEPFILTERS(__DS0Core), [IsGrandTotalRowTotal] = FALSE)

EVALUATE
	GROUPBY(
		__DS0CoreNoInstanceFiltersNoTotals,
		"MinAVG_TIME_RESOLVED", MINX(CURRENTGROUP(), [AVG_TIME_RESOLVED]),
		"MaxAVG_TIME_RESOLVED", MAXX(CURRENTGROUP(), [AVG_TIME_RESOLVED]),
		"MinMIN_TIME_RESOLVED", MINX(CURRENTGROUP(), [MIN_TIME_RESOLVED]),
		"MaxMIN_TIME_RESOLVED", MAXX(CURRENTGROUP(), [MIN_TIME_RESOLVED]),
		"MinMAX_TIME_RESOLVED", MINX(CURRENTGROUP(), [MAX_TIME_RESOLVED]),
		"MaxMAX_TIME_RESOLVED", MAXX(CURRENTGROUP(), [MAX_TIME_RESOLVED]),
		"MinOVER_SLA", MINX(CURRENTGROUP(), [OVER_SLA]),
		"MaxOVER_SLA", MAXX(CURRENTGROUP(), [OVER_SLA])
	)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC,
	'data_tiket'[additional_info_label_sub_sub_category],
	'data_tiket'[additional_info_label_sub_category]